ToName = fun (App) -> list_to_atom(hd(string:tokens(App,"-"))) end,

Apps = [list_to_atom(App)  || "applications/"++App = Dir <- filelib:wildcard("applications/*"), filelib:is_dir(Dir)],
Core = [list_to_atom(App)  ||         "core/"++App = Dir <- filelib:wildcard(        "core/*"), filelib:is_dir(Dir)],
Deps = [list_to_atom(App)  ||         "deps/"++App = Dir <- filelib:wildcard(        "deps/*"), filelib:is_dir(Dir)],

ToFilterOut = [rabbitmq_codegen
              ,'.erlang.mk'
              ,'ci.erlang.mk'
              ,'.settings'
              ,skel
              ,parse_trans
              ,meck
              ,'kazoo_slack'
              ,'exml'
              ,'escalus'
              ,'ananke'
              ,'amqp_cron'
              ,'amqp_leader'
              ,'amqp_dist'
              ],
Preparer = fun (List) -> [{E,load} || E <- List, not lists:member(E, ToFilterOut)] end,
Base = [runtime_tools
       ,wx
       ,observer
       ,debugger
       ,sasl
       ],
VSN = os:cmd("echo -n $(scripts/next_version 2>/dev/null)"),

[{lib_dirs, ["applications"
            ,"core"
            ,"deps"
            ]}

,{include_src, false}
,{include_erts, false}

,{generate_start_script, false}
,{extended_start_script, false}

,{sys_config, "rel/dev.sys.config"}
,{vm_args, "rel/dev.vm.args"}

,{overlay, [{copy, "../core/sup/sup", "{{output_dir}}/bin/"}
           ,{copy, "nodetool", "{{output_dir}}/bin/"}
           ,{template, "kazoo", "{{output_dir}}/bin/kazoo"}
          ]}
            
,{default_release, {kazoo, VSN}}
,{release, {kazoo, VSN}
 ,Base ++ Preparer(Apps ++ Core ++ Deps)
 }
] ++ [begin
       {ok, [{application, App, Settings}]} = file:consult(list_to_binary(["applications/", atom_to_list(App), "/ebin/", atom_to_list(App), ".app"])),
       AppDeps = proplists:get_value(applications, Settings, []),
       {release, {App, VSN}, Base ++ Preparer(AppDeps)}
      end
    || App <- Apps,
       not lists:member(App, ToFilterOut)
   ].
